config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'diagnoses#index'
  resources :users, only: [:edit, :update]
  resources :menus, only: [:new, :create , :destroy] do
    resources :diagnoses, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :user
  belongs_to :menu

end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user
  has_one    :diagnosis

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :menus
  has_many :diagnoses

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/diagnoses_controller.rb
class DiagnosesController < ApplicationController

  def index
    @diagnosis = Diagnosis.new
    @menu = Menu.new
    # @menu = Menu.find(params[:menu_id])
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menu = Menu.new
    # admin_user =  User.first 
    # @menu = Menu.find(params[:menu_id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to root_path
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    current_user.update(user_params)
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diagnoses_helper.rb
module DiagnosesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diagnoses/_diagnoses.html.erb
<%# <head> %>

<%# //jQueryのCDN %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/c.min.js"></script>
<script type="text/javascript"　src="../interview.js"></script>
<%# </head> %>

<%# <body> %>

<div class="choose_box">
   
<div id="q_01" class="fit">
 <p>質問1</p>
<ul class="flexbox fw">
<li class="even"><a class="btn" href="#q_02">選択肢1</a></li>
<li class="odd"> <a class="btn" href="#q_03">選択肢2</a></li>
<li class="odd"> <a class="btn" href="#q_04">選択肢3</a></li>
<li class="odd"> <a class="btn" href="#q_05">選択肢4</a></li>
</ul>
 </div>
 <!-- 最初の選択肢 -->
   
<div id="q_02" style="display: none;">
<p>質問2？</p>
<ul class="flexbox fw">
<li class="even"><a class="btn" href="#q_06">選択肢1-1</a></li>
<li class="odd"> <a class="btn" href="#q_07">選択肢1-2</a></li>
</ul>
</div>
<!-- 次の選択肢 -->
  
<div id="q_03" style="display: none;">
<p>質問2？</p>
<ul class="flexbox fw">
<li class="even"><a class="btn" href="#q_06">選択肢2-1</a></li>
<li class="odd"> <a class="btn" href="#q_07">選択肢2-2</a></li>
</ul>
</div>
<!-- 次の選択肢 -->
   
<div id="q_04" style="display: none;">
<p>質問2？</p>
<ul class="flexbox fw">
<li class="even"><a class="btn" href="#q_06">選択肢3-1</a></li>
<li class="odd"> <a class="btn" href="#q_07">選択肢3-2</a></li>
</ul>
</div>
<!-- 次の選択肢 -->
   
 <div id="q_05" style="display: none;">
<p>質問2？</p>
<ul class="flexbox fw">
<li class="even"><a class="btn" href="#q_06">選択肢4-1</a></li>
<li class="odd"> <a class="btn" href="#q_07">選択肢4-2</a></li>
</ul>
</div>
<!-- 次の選択肢 -->
   
   
 <div id="q_06" style="display: none;">
        <p>あなたにおすすめなのは…</p>
        <h4>『答え①』です！！</h4>
   <span><a class="btn" href="#q_01">もどる</a></span>
</div>
  
<!-- 選択肢の答え① -->
   
  <div id="q_07" style="display: none;">
        <p>あなたにおすすめなのは…</p>
        <h4>『答え②』です！！</h4>
     <span><a class="btn" href="#q_01">もどる</a></span>
</div>
  
<!-- 選択肢の答え② -->
</div>

<%# <script type="text/javascript">
$(function () {
    $(".btn").on("click", function () {
        $(this).closest("div").css("display", "none");
        id = $(this).attr("href");
        $(id).addClass("fit").show("slow");
    });
});
</script> %>

<%# </body> %>

app/views/diagnoses/_interview3.html.erb
<!DOCTYPE html>
<html>
  <head> 
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript"　src="../interview.js"></script>
  </head> 
  
  <body> 
  
    <div class="choose_box">
     
    <div id="q_01" class="fit">
    <p>質問1</p>
    <p>朝の目覚めは？</p>
    <ul class="flexbox fw">
    <li class="even"><a class="btn" href="#q_02" value= 3 >気持ちいい</a></li>
    <li class="odd"> <a class="btn" href="#q_02" value= 2 >普通</a></li>
    <li class="odd"> <a class="btn" href="#q_02" value= 1 >悪い</a></li>
    </ul>
    </div>
    <!-- 最初の選択肢 -->
      
    <div id="q_02" style="display: none;">
    <p>質問2</p>
    <p>布団に入ってから眠るまでの時間は？</p>
    <ul class="flexbox fw">
    <li class="even"><a class="btn" href="#q_03" value= 3 >10分以下</a></li>
    <li class="odd"> <a class="btn" href="#q_03" value= 2 >10分〜30分</a></li>
    <li class="odd"> <a class="btn" href="#q_03" value= 1 >30分以上</a></li>
    </ul>
    </div>
    <!-- 次の選択肢 -->
      
    <div id="q_03" style="display: none;">
    <p>質問3</p>
    <p>夜中目が覚める回数は？</p>
    <ul class="flexbox fw">
      <li class="even"><a class="btn" href="#q_04" value= 3 >0回</a></li>
      <li class="odd"> <a class="btn" href="#q_04" value= 2 >1回〜2回</a></li>
      <li class="odd"> <a class="btn" href="#q_04" value= 1 >3回以上</a></li>
    </ul>
    </div>
    <!-- 次の選択肢 -->
      
    <div id="q_04" style="display: none;">
    <p>質問4</p>
    <p>日中の眠気は？</p>
    <ul class="flexbox fw">
      <li class="even"><a class="btn" href="#q_05" value= 3 >全くない</a></li>
      <li class="odd"> <a class="btn" href="#q_05" value= 2 >時々ある</a></li>
      <li class="odd"> <a class="btn" href="#q_05" value= 1 >ある</a></li>
    </ul>
    </div>
    <!-- 次の選択肢 -->
      
    <div id="q_10" style="display: none;">
    <p>質問2？</p>
    <ul class="flexbox fw">
    <li class="even"><a class="btn" href="#q_06">選択肢4-1</a></li>
    <li class="odd"> <a class="btn" href="#q_07">選択肢4-2</a></li>
    </ul>
    </div>
    <!-- 次の選択肢 -->
      
      
    <div id="q_05" style="display: none;">
            <p>あなたにおすすめなのは…</p>
            <h4>『答え①』です！！</h4>
      <span><a class="btn" href="#q_01">もどる</a></span>
    </div>
      
    <!-- 選択肢の答え① -->
      
      <div id="q_07" style="display: none;">
            <p>あなたにおすすめなのは…</p>
            <h4>『答え②』です！！</h4>
        <span><a class="btn" href="#q_01">もどる</a></span>
    </div>
      
    <!-- 選択肢の答え② -->
    </div>

  </body>
</html>

app/views/diagnoses/_main_chat.html.erb
<div class="chat-header">
 <div class="left-header">
    <div class="header-title">
      <%= '睡眠診断(全4問)' %>
         <%# <%= @menu.name %> 
    </div>
  </div>
  <div class="right-header">
  <% if current_user.admin?  %>
    <div class="header-button">
      <%# <a href="#">Menuを終了する</a> %>
      <%# <%= link_to "Menuを終了する", menu_path(@menu), method: :delete %> 
    </div>
  <% end %>
  </div>
</div>

<div class="messages">
  <%= render partial: 'interview' %>
</div>


<%# <div class="form">
  <div class="form-input">
    <input class="form-message" placeholder= "type a message">
  </div>
  <input class="form-submit" type="submit" value="送信">
</div> %>

app/views/diagnoses/_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%= link_to current_user.name , edit_user_path(current_user) %>
  </div>
  <% if current_user.admin?  %>
  <div class="create-menu">
    <%= link_to "menuを作成する", new_menu_path %>
  </div>
  <% end %>
</div>

<div class="menus">
      
<%# <% current_user.menus.each do |menu| %> 
  <div class="menu">
    <div class="menu-name">
      <a href="#">睡眠診断</a> 
      <%# <%= link_to menu.name, menu_diagnoses_path(menu) %> 
    </div>
  </div>
  <%# <% end %> 
</div>

app/views/diagnoses/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "side_bar"%>
  </div>
  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiagnosisChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/index.html.erb
<div class='wrapper'>
  <div class='side-bar'>
    <%= render "messages/side_bar"%>
  </div>
</div>

app/views/menus/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @menu, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :Menu名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'Menu名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>作成者</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="menu[user_id]">
          <option value="">adminユーザーを選択してください</option>
            <% User.all.where(id: current_user.id).each do |user| %>
              <option value=<%=user.id%>><%= user.name %></option>
          <% end %>
        </select>

      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
        <%=link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>